[versions]
androidx-core-ktx = '1.9.0'
android-gradle-plugin = '7.4.2'


[libraries]
androidx-core-core-ktx = { module = 'androidx.core:core-ktx', version.ref = 'androidx-core-ktx' }


[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }